<?php

$smilies=array(
':s1e:'=>'smile.gif',
':s2e:'=>'yes.gif',
':s3e:'=>'mad.gif',
':s4e:'=>'blink.gif',
':s5e:'=>'censored.gif',
':s6e:'=>'cool.gif',
':s7e:'=>'crazyman.gif',
':s8e:'=>'dry.gif',
':s9e:'=>'help.gif',
':s10e:'=>'hmmm.gif',
':s11e:'=>'shuffle.gif',
':s12e:'=>'laugh.gif',
':s13e:'=>'ohmy.gif',
':s14e:'=>'ph34r.gif',
':s15e:'=>'rolleyes.gif',
':s16e:'=>'sad.gif',
':s17e:'=>'shit.gif',
':s18e:'=>'spade.gif',
':s19e:'=>'thumbdown.gif',
':s20e:'=>'thumbup.gif',
':s21e:'=>'tongue.gif',
':s22e:'=>'unsure.gif',
':s23e:'=>'wacko.gif',
':s24e:'=>'wink.gif',
':s25e:'=>'yahoo.gif',
':s11_closed423543e:'=>'huh.gif',
':s11_closed4567353e:'=>'biggrin.gif'
);

?>